services:
  netgear-playwright-factory-repair:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netgear-playwright-factory-repair
    volumes:
      - ./:/app
    working_dir: /app
    #command: sh -c "npm install && npx playwright install --with-deps && npm run test"
    #tty: true
    networks:
      default:
      vlandown:
        ipv4_address: 192.168.0.171

networks:
  default:
    driver: bridge
  vlandown:
    external: true
    ipam:
      config:
        - subnet: 192.168.0.0/24
