services:
  netgear-playwright-factory-repair:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netgear-playwright-factory-repair
    networks:
      default:
      vlandown:
        ipv4_address: 192.168.0.171
    restart: always

networks:
  default:
    driver: bridge
  vlandown:
    external: true
    ipam:
      config:
        - subnet: 192.168.0.0/24
